const theme = [
    {   
    "--background-gray": "green",
    "--box-darker-gray": "green",
    "--sender-color": "green",
    "--message-body-color": "green",
    "--hover-color": "green",
    "--selected-color": "green",
    "--emoji-background": "green",
    "--search-background": "green",
    "--divider-color": "green",
    "--icon-hover": "green",
    "--message-text-color": "green",
    "--list-box-color": "green",
    "--popup-background": "green",
    },
    {   
        "--background-gray": "brown",
        "--box-darker-gray": "brown",
        "--sender-color": "brown",
        "--message-body-color": "brown",
        "--hover-color": "brown",
        "--selected-color": "brown",
        "--emoji-background": "brown",
        "--search-background": "brown",
        "--divider-color": "brown",
        "--icon-hover": "brown",
        "--message-text-color": "brown",
        "--list-box-color": "brown",
        "--popup-background": "brown",
        },
    {   
    "--background-gray": "rgb(219, 218, 217)",
    "--box-darker-gray": "rgb(190, 189, 188)",
    "--sender-color": "rgb(91, 87, 83)",
    "--message-body-color": "rgb(91, 87, 83)",
    "--hover-color": "rgba(190, 189, 188, 0.5)",
    "--selected-color": "rgb(190, 189, 188)",
    "--emoji-background": "rgb(71, 67, 63)",
    "--search-background": "rgb(245, 245, 245)",
    "--divider-color": "rgba(71, 67, 63, 0.3)",
    "--icon-hover": "rgb(159, 178, 189)",
    "--message-text-color": "rgb(245, 245, 245)",
    "--list-box-color": "rgb(71, 67, 63)",
    "--popup-background": "rgb(245, 245, 245, 0.7)",
    },
    {   
        "--background-gray": "yellow",
        "--box-darker-gray": "yellow",
        "--sender-color": "yellow",
        "--message-body-color": "yellow",
        "--hover-color": "yellow",
        "--selected-color": "yellow",
        "--emoji-background": "yellow",
        "--search-background": "yellow",
        "--divider-color": "yellow",
        "--icon-hover": "yellow",
        "--message-text-color": "yellow",
        "--list-box-color": "yellow",
        "--popup-background": "yellow",
    },
    {   
        "--background-gray": "blue",
        "--box-darker-gray": "blue",
        "--sender-color": "blue",
        "--message-body-color": "blue",
        "--hover-color": "blue",
        "--selected-color": "blue",
        "--emoji-background": "blue",
        "--search-background": "blue",
        "--divider-color": "blue",
        "--icon-hover": "blue",
        "--message-text-color": "blue",
        "--list-box-color": "blue",
        "--popup-background": "blue",
    }
]

export { theme as default }
